---
# tasks file for dockerimage
- name: Create necessary directories
  file:
    path: "{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - "/docker/ghost"
    - "/docker/data"

- name: Copy ghost files to /suspicious/ghost
  copy:
    src: "{{ item }}"
    dest: "/docker/ghost/{{ item }}"
  with_items:
    - "Dockerfile"
    - "start.bash"

- name: Build Ghost container
  shell: docker build -t ghost .
  args:
    chdir: /docker/ghost
- name: Copy the data to the server
  copy:
    src: "ghost-data.tar.bz2"
    dest: "/docker/ghost-data.tar.bz2"

- name: Extract the ghost data
  unarchive: 
    copy: no 
    src: "/docker/ghost-data.tar.bz2" 
    dest: "/docker/data"
- name: Build Data Volume Container
  docker:
    image: centos:latest
    name: GHOSTDATA
    state: started
    volumes:
      - "/ghost-override"
    command: "/bin/sh"
- name: Clear the existing data
  docker:
    image: centos:latest
    command: "/bin/sh -c 'rm -rf /ghost-override/*'"
    name: namevolume
    volumes_from: GHOSTDATA
    state: running

- name: Replace the data
  docker:
    image: centos:latest
    command: "/bin/sh -c 'cp -r /suspicious-data/* /ghost-override'"
    volumes:
      - "/docker/data:/suspicious-data"
    volumes_from: GHOSTDATA
    state: running
- name: Restart Ghost
  docker:
    image: ghost
    ports: 2368:2368
    state: restarted
    volumes_from: GHOSTDATA

- name: Make sure that Ghost is running in the end
  docker:
    image: ghost
    ports: 2368:2368
    state: running
    volumes_from: GHOSTDATA

