---
# tasks file for apache
#tasks:
- name: install the apache
  yum: name=httpd state=latest
  notify:
  - restart httpd
  
#handlers:
 # - name: restart apache
  #  service: name=httpd state=restarted	

- name: restart apache
  service: name=httpd state=restarted		
