---
- name: install and start apache
  hosts: application
  #remote_user: amukherjee
  #become: yes
  #become_method: sudo

  tasks:
  - name: install apache
    yum: name=httpd state=present
    #become: yes
    #become_method: sudo

  - name: start and enable apache
    service: name=httpd state=started enabled=yes
    #become: yes
    #become_method: sudo

