---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:

  - name: install ntp
    yum: name=ntp state=installed 

  - name: write our ntp.conf
    copy: src=/home/ansible/ansible-demo/ntp.conf dest=/etc/ntp.conf mode=644 owner=root group=root
    notify: restart ntp

  - name: start ntp
    service: name=ntpd state=started

  handlers:

  - name: restart ntp
    service: name=ntpd state=restarted
