FROM ubuntu:latest
MAINTAINER Atanu Mukherjee <atanu.mukh728@gmail.com>
RUN apt-get update && apt-get install -y ruby ruby-dev
CMD while true; do echo hello world; sleep 10; done
#ENTRYPOINT echo Hello World 
#CMD "update &"

#FROM centos:latest
#ADD test.sh /
#RUN chmod +x /test.sh
##CMD "Hello World!"
#CMD ["/bin/sh","/test.sh"]
#ENTRYPOINT ./test.sh

