---
# tasks file for estdockerimage
- name: Create necessary directories
  file:
    path: "{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - "/docker/testdata"

- name: Copy test files to /docker/testdata
  copy:
    src: "{{ item }}"
    dest: "/docker/testdata/{{ item }}"
  with_items:
    - "Dockerfile"
    - "test.sh"

- name: Build Test container
  shell: docker build -t testimage:latest .
  args:
    chdir: /docker/testdata


- name: data container
  docker:
   name: mydata
   image: testimage:latest
   docker_user: "1001:980"
   state: started
   privileged: false
   stop_timeout: 30
   restart_policy: on-failure
   restart_policy_retry: 5
   volumes:
    - /data
   #command: "sh test.sh"
#- name: start the container
  #shell: docker start mydata
  #shell: docker run  -v /data --name mydata testimage /bin/bash
